AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  VotesTable:
    Type: AWS::Serverless::SimpleTable
  VoteSpacesTabs:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: lambda_function.lambda_handler
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME:
            Ref: VotesTable
      Events:
        Vote:
          Type: Api
          Properties:
            Path: /
            Method: post
        Show:
          Type: Api
          Properties:
            Path: /
            Method: get
      CodeUri: s3://samexample2/0a5f776094060c7b4b3f5c53afcd73a6
Outputs:
  ShowApi:
    Description: API Gateway endpoint URL for Prod stage for Votes function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
